# Generated by Django 4.2.6 on 2024-02-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city_origin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country_origin',
        ),
        migrations.AddField(
            model_name='additionaldata',
            name='city_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='additionaldata',
            name='country_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
