# Generated by Django 4.2.6 on 2024-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_additionaldata_age_additionaldata_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldata',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
