# Generated by Django 4.2.6 on 2024-05-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_additionaldata_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldata',
            name='age',
        ),
    ]
