# Generated by Django 4.2.6 on 2024-05-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_budget_trip_expense_costestimation_budget_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='accomadation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='activities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='food',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='other',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='transportation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
