# Generated by Django 4.2.6 on 2024-05-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_budget_accomadation_budget_activities_budget_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='accomadation',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='food',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='other',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='transportation',
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=15)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.budget')),
            ],
        ),
    ]
