# Generated by Django 4.2.6 on 2024-05-28 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_budget_accomadation_remove_budget_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip', unique=True),
        ),
    ]
