# Generated by Django 4.2.6 on 2024-05-28 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_budgetitem_date_alter_budget_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='description',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
