# Generated by Django 4.2.6 on 2024-05-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_trip_jwt_token_trip_uuid_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='uuid_expiration_date',
            new_name='n_uuid_expiration_date',
        ),
    ]
