# Generated by Django 4.2.6 on 2024-05-29 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_trip_n_uuid_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='jwt_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='nn_uuid_expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
