# Generated by Django 4.2.6 on 2024-05-31 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_trip_jwt_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SharedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
