# Generated by Django 4.2.6 on 2024-06-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_trip_is_shared_sharedtrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='nn_uuid_expiration_date',
        ),
    ]
