# Generated by Django 4.2.6 on 2024-06-01 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_trip_nn_uuid_expiration_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharedtrip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sharedtrip',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sharedtrip',
            unique_together={('trip', 'email')},
        ),
        migrations.RemoveField(
            model_name='sharedtrip',
            name='user',
        ),
    ]
