# Generated by Django 4.2.6 on 2024-06-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_sharedtrip_unique_together_sharedtrip_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldata',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='additionaldata',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='additionaldata',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
