# Generated by Django 4.2.6 on 2024-06-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtrip',
            name='archivedTrips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='archivedTrips',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
