# Generated by Django 4.2.6 on 2024-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_blogcomment_blogpost_userbloglikes_blogcomment_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='PRcard',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Visa',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_card',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='passport',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
