# Generated by Django 4.2.6 on 2024-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='brt',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='trt',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
