# Generated by Django 4.2.6 on 2024-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_trip_brt_trip_trt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
